/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface PmsAccordion {
    'color': string;
    'description': string;
    'label': string;
    'width': string;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLPmsAccordionElement extends Components.PmsAccordion, HTMLStencilElement {}
  var HTMLPmsAccordionElement: {
    prototype: HTMLPmsAccordionElement;
    new (): HTMLPmsAccordionElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'pms-accordion': HTMLPmsAccordionElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface PmsAccordion {
    'color'?: string;
    'description'?: string;
    'label'?: string;
    'onOnToggle'?: (event: CustomEvent<any>) => void;
    'width'?: string;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'pms-accordion': PmsAccordion;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'pms-accordion': LocalJSX.PmsAccordion & JSXBase.HTMLAttributes<HTMLPmsAccordionElement>;
    }
  }
}


